version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - pundit-community/dependabot-reviewers
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rubocop:
        patterns:
          - "rubocop*"
    reviewers:
      - pundit-community/dependabot-reviewers
