require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 2
