require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - coverage/**/*
    - doc/**/*
    - vendor/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 2
