plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - coverage/**/*
    - doc/**/*
    - vendor/**/*

# Configured to allow the use of `does_not_match?`, as it aligns with the RSpec Matcher Protocol.
# This method is part of RSpec's internal API for defining custom matchers.
# Reference: https://www.rubydoc.info/github/rspec/rspec-expectations/RSpec/Matchers/MatcherProtocol#does_not_match%3F-instance_method
Naming/PredicateName:
  AllowedMethods:
    - does_not_match?

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 2
