name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']
        channel: ['stable']

        include:
          - ruby-version: 'head'
            channel: 'experimental'

    continue-on-error: ${{ matrix.channel != 'stable' }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        rubygems: latest
    - name: Run specs
      run: bundle exec rake
